<project xmlns:if="ant:if" xmlns:unless="ant:unless" name="svqk-cicd" default="install">

  <taskdef resource="net/sf/antcontrib/antlib.xml" />

  <target name="generate">
    <loadfile property="metadata" srcFile="${metadata.path}" />
    <script language="graal.js" src="${basedir}/src/main/build-template-data.js" />
    <echo file="${project.build.directory}/template-data.json" message="${template.data}"
      encoding="UTF-8" />
  </target>
</project>