<project xmlns:if="ant:if" xmlns:unless="ant:unless" name="svqk-cicd" default="install">

  <taskdef resource="net/sf/antcontrib/antlib.xml" />

  <macrodef name="exec-tbdt">
    <attribute name="template" />
    <attribute name="input" />
    <attribute name="output" />
    <attribute name="query" />

    <sequential>
      <java jar="${tbdt.jar}" fork="true" failonerror="true">
        <arg line="-t @{template} -i @{input} -o @{output} -q &quot;@{query}&quot;" />
      </java>
    </sequential>
  </macrodef>

  <target name="generate">
    <exec-tbdt
      template="${basedir}/src/main/resources/template-data.ftl"
      input="${metadata.path}"
      output="${project.build.directory}/template-data.json"
      query="$" />
  </target>
</project>