<project xmlns:if="ant:if" xmlns:unless="ant:unless" name="svqk-cicd" default="install">

  <taskdef resource="net/sf/antcontrib/antlib.xml" />

  <property name="prjdir" value="${basedir}/.." />

  <condition property="mvn.cmd" value="${prjdir}/mvnw.cmd" else="${prjdir}/mvnw">
    <os family="windows" />
  </condition>

  <target name="generate">
    <loadfile property="metadata" srcFile="${metadata.path}" />
    <script language="javascript" src="${basedir}/src/main/build-template-data.js" />
  </target>
</project>