<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- The Basics -->
  <groupId>dev.aulait.svqk</groupId>
  <artifactId>svqk-generator-tbdt</artifactId>
  <packaging>pom</packaging>

  <parent>
    <groupId>dev.aulait.svqk</groupId>
    <artifactId>svqk</artifactId>
    <version>0.10-SNAPSHOT</version>
    <relativePath>../</relativePath>
  </parent>

  <properties>
    <prjdir>${project.basedir}/..</prjdir>
    <metadata.path>${prjdir}/svqk-generator/src/main/resources/jeg-metadata.json</metadata.path>
    <tbdt.jar>${project.basedir}/src/main/resources/tbdt-core-0.8-SNAPSHOT-all-deps.jar</tbdt.jar>

    <ant.file>${project.basedir}/build.xml</ant.file>

    <sonar.skip>true</sonar.skip>
  </properties>

  <!-- Build -->
  <build>
    <defaultGoal>antrun:run</defaultGoal>

    <plugins>
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <configuration>
          <target>
            <ant antfile="${ant.file}" target="${ant.target}" />
          </target>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>